version: "3"
services:
  nodejs:
    container_name: nodejs
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db
    working_dir: /data/db
